import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from datetime import datetime, timedelta
from ortools.sat.python import cp_model

from engine import HeterogeneousIngestionEngine, MultiObjectiveScheduler, OnlineFeedbackLearningLoop


def generate_raw_telemetry():
    """Synthetic telemetry generator for local demo/testing."""
    now = datetime.now()
    raw_data = []
    for i in range(1, 26):
        has_brand = np.random.random() < 0.3
        maint_logs = [
            "LOG: System check complete. Clear.",
            "CRITICAL: Brake caliper wear limits breached. Immediate action required.",
            "WARNING: Minor axle maintenance checklist overdue.",
            "LOG: Routine HVAC filter replacement scheduled."
        ]
        raw_data.append({
            "id_string": f"TS-{i:03d}",
            "sig_cert": (now + timedelta(days=int(np.random.randint(-2, 60)))).isoformat(),
            "brk_log": (now + timedelta(days=int(np.random.randint(5, 70)))).strftime("%Y-%m-%d %H:%M:%S"),
            "safety_meta": (now + timedelta(days=int(np.random.randint(10, 50)))).isoformat(),
            "unstructured_maintenance_text": np.random.choice(maint_logs, p=[0.75, 0.05, 0.1, 0.1]),
            "odometer_reading": int(np.random.randint(50000, 110000)),
            "ad_contract_active": has_brand,
            "contract_client": np.random.choice(['TechCorp', 'MediaGroup', 'RetailCorp']) if has_brand else None,
            "hours_owed": int(np.random.randint(4, 8)) if has_brand else 0,
            "cleaned_at": (now - timedelta(days=int(np.random.randint(1, 10)))).isoformat(),
            "bay_location": int(np.random.randint(1, 26))
        })
    return raw_data


def main():
    st.set_page_config(page_title="AI Train Scheduler", layout="wide")
    st.markdown('<h1 style="color:#1E40AF; text-align:center;">🚇 AI-Driven Train Induction & Scheduling Platform</h1>', unsafe_allow_html=True)

    # Session state initialization
    if 'train_data' not in st.session_state:
        st.session_state.train_data = HeterogeneousIngestionEngine.parse_telemetry(generate_raw_telemetry())
    if 'optimization_results' not in st.session_state:
        st.session_state.optimization_results = None
    if 'ml_weights' not in st.session_state:
        st.session_state.ml_weights = {'mileage': 1.0, 'certificates': 1.2, 'stabling': 0.6}

    df = st.session_state.train_data
    required_trains = 14

    # Sidebar: optimization controls
    with st.sidebar:
        st.header("⚙️ Optimization Parameters")
        st.write("Weights are adjusted over time by the feedback loop based on supervisor overrides.")

        st.number_input("Mileage Balance Weight", value=st.session_state.ml_weights['mileage'], disabled=True)
        st.number_input("Certificate Safety Weight", value=st.session_state.ml_weights['certificates'], disabled=True)
        st.number_input("Stabling Friction Weight", value=st.session_state.ml_weights['stabling'], disabled=True)

        if st.button("🚀 Run Multi-Objective Solver", type="primary"):
            df_diagrams = pd.DataFrame([
                {"Diagram_ID": f"D{i:02d}", "Depart_Time": datetime.now() + timedelta(hours=i),
                 "Planned_Km": int(np.random.randint(130, 210))} for i in range(1, required_trains + 1)
            ])
            df_bays = pd.DataFrame([{"Bay": b, "ExitCost": (1 if b <= 8 else (3 if b <= 16 else 6))} for b in range(1, 26)])

            scheduler = MultiObjectiveScheduler(st.session_state.ml_weights)
            st.session_state.optimization_results = scheduler.build_and_solve(df, df_diagrams, df_bays)
            st.success("Optimal schedule generated by CP-SAT engine.")

    tab1, tab2, tab3 = st.tabs(["📊 Data Ingestion", "🎯 Schedule & XAI", "🔄 Feedback Loop"])

    with tab1:
        st.subheader("Normalized Fleet Data")
        st.dataframe(df, use_container_width=True)

    with tab2:
        st.subheader("Schedule & Per-Train Cost Attribution")
        res = st.session_state.optimization_results

        if res and res.get("status") in (cp_model.OPTIMAL, cp_model.FEASIBLE):
            svc_df = pd.DataFrame(res["service"])
            st.dataframe(svc_df, use_container_width=True)

            st.markdown("### 👁️ Objective Penalty Breakdown")
            selected_train = st.selectbox("Select train:", svc_df["Train_ID"].tolist())

            if selected_train in res["xai_attributions"]:
                attr = res["xai_attributions"][selected_train]
                fig = go.Figure(go.Waterfall(
                    orientation="v",
                    measure=["relative", "relative", "relative"],
                    x=list(attr.keys()),
                    y=list(attr.values()),
                    textposition="outside"
                ))
                fig.update_layout(title=f"Cost breakdown for {selected_train} (lower cost = preferred)")
                st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("Run the solver from the sidebar to populate the schedule.")

    with tab3:
        st.subheader("Supervisor Feedback → Weight Update")
        st.write("Flag an issue with the generated schedule to trigger an online weight update.")

        rejection_profile = st.radio("Issue type:", [
            "HIGH_MILEAGE_VARIANCE",
            "SAFETY_MARGIN_VIOLATION",
            "STABLING_BOTTLENECK"
        ])

        if st.button("Apply Weight Update"):
            loop = OnlineFeedbackLearningLoop()
            st.session_state.ml_weights = loop.compute_gradient_update(st.session_state.ml_weights, rejection_profile)
            st.rerun()


if __name__ == "__main__":
    main()
